--
-- PostgreSQL database dump
--

\restrict q1HP1oOEafXi0c40OoqARfvH3DlfiQUlUD9QhAbhSuk0hN7G6zYNfUfd4IZZLtz

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-31 23:27:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16435)
-- Name: orders; Type: TABLE; Schema: public; Owner: Amogh
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    token_number integer,
    total_amount integer,
    user_id bigint NOT NULL
);


ALTER TABLE public.orders OWNER TO "Amogh";

--
-- TOC entry 221 (class 1259 OID 16434)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: Amogh
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16422)
-- Name: users; Type: TABLE; Schema: public; Owner: Amogh
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    auth_provider character varying(255),
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255),
    registered boolean NOT NULL,
    role character varying(255)
);


ALTER TABLE public.users OWNER TO "Amogh";

--
-- TOC entry 219 (class 1259 OID 16421)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: Amogh
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4866 (class 2606 OID 16442)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: Amogh
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 16433)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: Amogh
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4864 (class 2606 OID 16431)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: Amogh
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4867 (class 2606 OID 16443)
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: Amogh
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2025-12-31 23:27:23

--
-- PostgreSQL database dump complete
--

\unrestrict q1HP1oOEafXi0c40OoqARfvH3DlfiQUlUD9QhAbhSuk0hN7G6zYNfUfd4IZZLtz

